#platform :ios, "10.0"
use_frameworks!

target 'ChatChat' do
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Google/SignIn'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'JSQMessagesViewController'
  pod 'Firebase/Core'
  pod 'SDWebImage', '~>3.8'
  pod 'NVActivityIndicatorView'
end
